### ISSUE TITLE
TYPO3 - 8 don't work if sys ext backend backendimage is set

### ISSUE THREAD

**Issue by Teisi** [SvenJuergens/belogin_images#1]
Hello,

can you please add this hint to the docu? :)
Cause i run into this "problem", and i have searched for a while... 

Thx.

**Comment by SvenJuergens** [comment]
hey @Teisi 

sorry for the late response, i got no information about that ticket.
I have just released a new version in the ter, which should then also work with your use case.

Best Regards
Sven
