### ISSUE TITLE
Unsplash doesn't work anymore

### ISSUE THREAD

**Issue by simonschaufi** [SvenJuergens/belogin_images#11]
https://source.unsplash.com/1600x900/?nature gives me 404 error

This url is the default url in v5.0.0

**Comment by SvenJuergens** [comment]
hi @simonschaufi 

you are right, since unsplash has removed this API endpoint, i should probably remove unsplash from the extension as well

**Comment by simonschaufi** [comment]
yes, please also backport this

**Comment by SvenJuergens** [comment]
hi @simonschaufi, thank you for your feedback. I have now put new versions online

**Comment by simonschaufi** [comment]
thank you! :tada:
