### ISSUE TITLE
Error when Folder is selected

### ISSUE THREAD

**Issue by ses2013** [SvenJuergens/belogin_images#5]
backend Error
typo3 11.5.24
belogin_images 4.0.1

PHP Warning: Undefined array key "author" in /home_pr5/c/o/XXX/htdocs/xxx/typo3conf/ext/belogin_images/Classes/Services/ServiceWrapper.php line 39

**Comment by SvenJuergens** [comment]
Hi @ses2013 ,

thanks for Reporting :)
I have uploaded the version 4.0.2 to the TER, the bug is already fixed there.

Best Regards
Sven
