### ISSUE TITLE
Allow EXT: in source folder

### ISSUE THREAD

**Issue by echavaillaz** [SvenJuergens/belogin_images#8]
Hi,

A great feature would to allow using "EXT:..." instead of "fileadmin/" when using folder as source.

Thanks

**Comment by SvenJuergens** [comment]
hi @echavaillaz Just out of curiosity, can you give me a use case? How and where do you have images in the extension folders? :)

**Comment by echavaillaz** [comment]
For example in an extension used as site package. I have some images in my Resources folder of my extension. And I want to show them to the customer. But I don't want to let them choose (or add/delete) images.

**Comment by SvenJuergens** [comment]
@echavaillaz should be work now with Version 5.1
